version: '3'

volumes:
  tesla_http_proxy:
    external: true

services:   
  tesla_http_proxy:
    container_name: tesla_http_proxy
    image: "iainbullock/tesla_http_proxy:latest"
 
    environment:
      - TZ='Europe/London'
      - CLIENT_ID='client_id'
      - CLIENT_SECRET='client_secret'
      - DOMAIN='tesla.example.com' # Public FQDN 
      - PROXY_HOST='hostname.local' # Local hostname (not IP) of this docker host
      - REGION='Europe, Middle East, Africa' # Change to match your region
      
    stdin_open: true
    tty: true         
   
    entrypoint: "/app/run.sh"
    working_dir: /app

    volumes:
      - tesla_http_proxy:/data
      # Webserver root for the $DOMAIN virtual server. Change the path according to your webserver setup. Path must exist or this container won't start
      - type: bind
        source: /var/lib/docker/volumes/nginx/_data/tesla_http_proxy
        target: /share/nginx
      # Path to tesla_http_proxy directory inside /config on Home Assistant instance. Change according to your HA setup. Path must exist or this container won't start
      - type: bind
        source: /var/lib/docker/volumes/home-assistant/_data/tesla_http_proxy
        target: /share/home-assistant
        
    network_mode: bridge
    ports:
      - 4430:443
      - 8099:8099 

    restart: no
    #restart: unless-stopped  
